[package]
name = "graphene-cli"
version = "0.0.0"
authors = ["Luc Street <lucis-fluxum@users.noreply.github.com>"]
description = "..."
repository = "https://github.com/lucis-fluxum/graphene-cli"
license = "MIT"
edition = "2018"

[dependencies]
abscissa_core = { version = "0.5.2", features = ["gimli-backtrace"] }
gumdrop = "0.7"
serde = { version = "1", features = ["serde_derive"] }
thiserror = "1"

[dev-dependencies]
abscissa_core = { version = "0.5.2", features = ["testing"] }
once_cell = "1.2"

